version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: app-dynamodb
    hostname: app-dynamodb
    volumes:
      - app_dynamodb:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    ports:
      - '8002:8000'
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath .'
    restart: unless-stopped

  dynamodb_admin:
    image: aaronshaf/dynamodb-admin
    container_name: app-dynamodb_admin
    ports:
      - '8001:8001'
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
    restart: unless-stopped

  dynamodb_TuesHey_migrator:
    image: banst/awscli
    container_name: app-dynamodb_TuesHey_migrator
    working_dir: /home/dynamodblocal
    command: dynamodb create-table --cli-input-json file://TuesHey.json --endpoint-url http://dynamodb:8000
    volumes:
      - ./backend/database:/home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=unicorn
      - AWS_SECRET_ACCESS_KEY=magical_password
      - AWS_DEFAULT_REGION=ap-southeast-1
    depends_on:
      - dynamodb

  dynamodb_TuesHeySeed0:
    image: banst/awscli
    container_name: app-dynamodb_TuesHeySeed1
    working_dir: /home/dynamodblocal
    command: dynamodb batch-write-item --request-items file://TuesHeySeed0.json --endpoint-url http://dynamodb:8000 && dynamodb batch-write-item --request-items file://TuesHeySeederGroup2.json --endpoint-url http://dynamodb:8000 && dynamodb batch-write-item --request-items file://TuesHeySeederGroup3.json --endpoint-url http://dynamodb:8000
    volumes:
      - ./backend/database:/home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=unicorn
      - AWS_SECRET_ACCESS_KEY=magical_password
      - AWS_DEFAULT_REGION=ap-southeast-1
    depends_on:
      - dynamodb_TuesHey_migrator
      - dynamodb
    restart: on-failure

  dynamodb_TuesHeySeed1:
    image: banst/awscli
    container_name: app-dynamodb_TuesHeySeed2
    working_dir: /home/dynamodblocal
    command: dynamodb batch-write-item --request-items file://TuesHeySeed1.json --endpoint-url http://dynamodb:8000 && dynamodb batch-write-item --request-items file://TuesHeySeederGroup2.json --endpoint-url http://dynamodb:8000 && dynamodb batch-write-item --request-items file://TuesHeySeederGroup3.json --endpoint-url http://dynamodb:8000
    volumes:
      - ./backend/database:/home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=unicorn
      - AWS_SECRET_ACCESS_KEY=magical_password
      - AWS_DEFAULT_REGION=ap-southeast-1
    depends_on:
      - dynamodb_TuesHey_migrator
      - dynamodb
    restart: on-failure

volumes:
  app_dynamodb:
    driver: local
