org: si2222
app: uni-connector
component: express
name: backend

inputs:
  src:
    src: ./
    hook: npm run build
    dist: build
  roleName: serverRole
  region: ap-southeast-2
  env:
    ENVIRONMENT: production
